spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      retry:
        enabled: false
#    config:
#      fail-fast: true
#      retry:
#        initial-interval: 5000
#        max-attempts: 10
#        max-interval: 5000
#        multiplier: 1.2
server:
  port: 7777

#application:
#  api-routes:
#    - id: "library-client"
#      from: "library"
#      to: "lb://LIBRARY-CLIENT"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30

