version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8189:8189"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mainDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

    depends_on:
      - postgres

  postgres:
    image: "postgres:17"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mainDB
    ports:
      - "5430:5432"