server:
  port: 8189
  servlet:
    context-path: /library
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/mainDB
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  data:
    rest:
      basePath: /datarest
      default-page-size: 20
  liquibase:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
      roles: "ADMIN"
  health:
    defaults:
      enabled: true

logging:
  level:
    root: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  file.name: ./log/library.log




